---
name: "PR - Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
